apiVersion: v1
kind: Service
metadata:
  name: online-exam-sys-service
spec:
  selector:
    app: online-exam-sys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the service externally (for cloud providers)

